/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2016-01-18 05:48:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.backend.organization;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class organization_005fpermission_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/common/taglibs.jsp", Long.valueOf(1450659192538L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write(' ');
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<table id=\"datagrid-permission-list\"></table>\r\n");
      out.write("<div id='datagrid-permission-toolbar' class=\"datagrid-toolbar\">\r\n");
      out.write("\t<div class=\"toolbar-buttons\">\r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton\" onclick=\"pCrud.add();return false;\" data-options=\"iconCls:'icon-add',plain:true\">添加</a>\r\n");
      out.write("       \t<a class=\"datagrid-btn-separator no-float\"></a>\r\n");
      out.write("\t</div>   \t\t\r\n");
      out.write("\t<div class=\"searchForm\">\t\t\t\t\t\r\n");
      out.write("\t\t<div class=\"container_16 no-margin\">\r\n");
      out.write("\t\t\t<div class=\"grid_g\">\t\t\r\n");
      out.write("\t\t\t\t<div class=\"grid_3 align-right height-30\" ><h5>当前组织架构：</h5></div>\t\t\r\n");
      out.write("\t\t\t\t<div class=\"grid_13 height-30\"><h5>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${organization.parentNames}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</h5></div>\t\t\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t\t<div class=\"grid_g\">\t\t\r\n");
      out.write("\t\t\t\t<div class=\"grid_3 align-right height-30\"><label>负责人：</label></div>\r\n");
      out.write("\t\t\t\t<div class=\"grid_5\"><input class=\"easyui-selecttextbox\" name=\"director.id\" id=\"organizationDirector\" data-options=\"value: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${organization.director.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("', text : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${organization.director.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("', buttonIcon: 'icon-search', width: '100%'\" ></div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t</div>\t\t\t\r\n");
      out.write("\t</div>\t\t\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"datagrid-permission-row-toolbar\" class=\"hidden\">\r\n");
      out.write("\t<div id=\"datagrid-permission-row-toolbar-browse-row.index\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" title=\"删除当前记录\" onclick=\"pCrud.del(row.id, row.index);return false;\" data-options=\"iconCls:'icon-remove', plain:true\"></a>\r\n");
      out.write("\t</div>   \r\n");
      out.write("\t<div id=\"datagrid-permission-row-toolbar-save-row.index\" style=\"display:none\" >\r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton\" title=\"保存当前记录\" onclick=\"pCrud.saveRow();return false;\" data-options=\"iconCls:'icon-save', plain:true\"></a>\r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton\" title=\"取消修改\" onclick=\"pCrud.cancelRow();return false;\" data-options=\"iconCls:'icon-undo', plain:true\"></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\t\r\n");
      out.write("\t\tif (typeof ryUILib == 'undefined') {\r\n");
      out.write("\t\t\tbase.loadJs(contextPath + '/static/js/easyuiDataGrid.js');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar dataGridOptions = {\r\n");
      out.write("\t\t\tpagination : false,\r\n");
      out.write("\t\t\ttoolbar : '#datagrid-permission-toolbar',\r\n");
      out.write("\t\t\tcolumns : [ [ {\r\n");
      out.write("\t\t\t\tfield : 'name',\r\n");
      out.write("\t\t\t\ttitle : '可查看数据人员',\r\n");
      out.write("\t\t\t\twidth : 10,\r\n");
      out.write("\t\t\t\teditor : {\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\ttype:'selecttextbox',\r\n");
      out.write("\t\t\t\t\toptions :{\r\n");
      out.write("\t\t\t\t\t\twidth: '100%',\r\n");
      out.write("\t\t\t\t\t\theight : 39,\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t}] ],\r\n");
      out.write("\t\t\tonBeginEdit : function(index, row) {\r\n");
      out.write("\t\t\t\tvar nameEditor = $(this).datagrid('getEditor', {\r\n");
      out.write("\t\t\t\t\tindex : index,\r\n");
      out.write("\t\t\t\t\tfield : 'name'\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tif (nameEditor == null) {\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tcommonSelect.initSelectEmployee({\r\n");
      out.write("\t\t\t\t\tselecttextboxId : nameEditor.target,\r\n");
      out.write("\t\t\t\t\tsetValueCallback : function(text, value){\r\n");
      out.write("\t\t\t\t\t\trow.id = value;\r\n");
      out.write("\t\t\t\t\t\trow.name = text;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\t\t\t\t\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tvar options = {\r\n");
      out.write("\t\t\taddCkColumn : false,\r\n");
      out.write("\t\t\tdataGridId : '#datagrid-permission-list',\r\n");
      out.write("\t\t\trowToolbarId : '#datagrid-permission-row-toolbar',\r\n");
      out.write("\t\t\teditMode : 'cell',\r\n");
      out.write("\t\t\turl : {\r\n");
      out.write("\t\t\t\t//urlPrefix : contextPath + '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${controllerConfig.urlPrefix}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',\r\n");
      out.write("\t\t\t\tjsonListUrl : contextPath + '/backend/organization/getOrganizationPermissionJson/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${organization.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tedatagrid:{\t\t\t\t\r\n");
      out.write("\t\t\t\tdefaultEditField: 'name'\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tpCrud = ryUILib.EasyuiDataGrid(options, dataGridOptions);\r\n");
      out.write("\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\tcommonSelect.initSelectEmployee({selecttextboxId : '#organizationDirector'});\r\n");
      out.write("\t\t}, 300);\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/jsp/common/taglibs.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("contextPath");
    // /WEB-INF/jsp/common/taglibs.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/common/taglibs.jsp(7,0) '${pageContext.request.contextPath}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(null);
    // /WEB-INF/jsp/common/taglibs.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("webAppTitle");
    // /WEB-INF/jsp/common/taglibs.jsp(8,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/common/taglibs.jsp(8,0) '奥马导购移动端管理系统'",_el_expressionfactory.createValueExpression("奥马导购移动端管理系统",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }
}
