/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-12-07 02:00:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.weixin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chat_005fdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/common/taglibs.jsp", Long.valueOf(1448422453201L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write(' ');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"page\" id=\"chat_detail\">\r\n");
      out.write("\t<header class=\"bar bar-nav\">\r\n");
      out.write("\t    <a class=\"button button-link button-nav pull-left back\" href=\"/demos/bar\">\r\n");
      out.write("\t      <span class=\"icon icon-left\"></span>\r\n");
      out.write("\t      返回\r\n");
      out.write("\t    </a>\r\n");
      out.write("\t    <a class=\"button button-link button-nav pull-right\">\r\n");
      out.write("\t      下一步\r\n");
      out.write("\t      <span class=\"icon icon-right\"></span>\r\n");
      out.write("\t    </a>\r\n");
      out.write("\t    <h1 class=\"title\">标题</h1>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- \r\n");
      out.write("\t<nav class=\"bar bar-tab\">\r\n");
      out.write("\t    <a class=\"tab-item active\" href=\"#\">\r\n");
      out.write("\t      Label\r\n");
      out.write("\t    </a>\r\n");
      out.write("\t    <a class=\"tab-item\" href=\"#\">\r\n");
      out.write("\t      Label\r\n");
      out.write("\t    </a>\r\n");
      out.write("\t    <a class=\"tab-item\" href=\"#\">\r\n");
      out.write("\t      Label\r\n");
      out.write("\t    </a>\r\n");
      out.write("   </nav>\r\n");
      out.write("    -->\r\n");
      out.write("\t<div class=\"content\">\r\n");
      out.write("\t    <!-- 这里是页面内容区 -->\r\n");
      out.write("\t    <div class=\"content1 content-msg-detail\">\r\n");
      out.write("\t\t\t<ul class=\"msg-detail-list\" id=\"j-msg-detail-list\">\r\n");
      out.write("\t\t\t\t<li class=\"time\">14:53</li>\r\n");
      out.write("\t\t\t\t<li class=\"left\">\r\n");
      out.write("\t\t\t\t\t<section class=\"photo\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"src/images/msg_p5.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t<section class=\"msg\">账号发来 先给你打100万 </section>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"right\">\r\n");
      out.write("\t\t\t\t\t<section class=\"msg\">好的，土豪</section>\r\n");
      out.write("\t\t\t\t\t<section class=\"photo\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"src/images/msg_p6.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"time\">14:53</li>\r\n");
      out.write("\t\t\t\t<li class=\"left\">\r\n");
      out.write("\t\t\t\t\t<section class=\"photo\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"src/images/msg_p5.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t<section class=\"msg\">账号发来 先给你打100万 </section>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"right\">\r\n");
      out.write("\t\t\t\t\t<section class=\"msg\">好的，土豪</section>\r\n");
      out.write("\t\t\t\t\t<section class=\"photo\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"src/images/msg_p6.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"time\">14:53</li>\r\n");
      out.write("\t\t\t\t<li class=\"left\">\r\n");
      out.write("\t\t\t\t\t<section class=\"photo\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"src/images/msg_p5.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t<section class=\"msg\">账号发来 先给你打100万 </section>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"right\">\r\n");
      out.write("\t\t\t\t\t<section class=\"msg\">好的，土豪</section>\r\n");
      out.write("\t\t\t\t\t<section class=\"photo\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"src/images/msg_p6.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"time\">14:53</li>\r\n");
      out.write("\t\t\t\t<li class=\"left\">\r\n");
      out.write("\t\t\t\t\t<section class=\"photo\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"src/images/msg_p5.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t<section class=\"msg\">账号发来 先给你打100万 </section>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"right\">\r\n");
      out.write("\t\t\t\t\t<section class=\"msg\">好的，土豪</section>\r\n");
      out.write("\t\t\t\t\t<section class=\"photo\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"src/images/msg_p6.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"time\">14:53</li>\r\n");
      out.write("\t\t\t\t<li class=\"left\">\r\n");
      out.write("\t\t\t\t\t<section class=\"photo\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"src/images/msg_p5.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t<section class=\"msg\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"src/images/msg_p6.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"right\">\r\n");
      out.write("\t\t\t\t\t<section class=\"msg\">好的，土豪</section>\r\n");
      out.write("\t\t\t\t\t<section class=\"photo\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"src/images/msg_p6.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t   <div class=\"keyborad\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"toolbar messagebar key_inp\" >\r\n");
      out.write("      <div class=\"toolbar-inner\">\r\n");
      out.write("        <a href=\"javascript:void(0);\" class=\"link icon-only\"><i class=\"icon icon_emoji voice\"></i></a>\r\n");
      out.write("        <textarea placeholder=\"Message\" id=\"message_box\"></textarea>\r\n");
      out.write("        <a href=\"javascript:void(0);\" class=\"link icon-only\"><i class=\"icon icon_emoji _emoji\"></i></a>\r\n");
      out.write("        <a href=\"javascript:void(0);\" class=\"link icon-only option\"><i class=\"icons icon_emoji more_option\"></i></a>\r\n");
      out.write("        <a href=\"javascript:xx_send_chat_text();\" class=\"link send-message\"><span class=\"mes_send\">发送</span></a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"toolbar messagebar key_voice\" >\r\n");
      out.write("      <div class=\"toolbar-inner\">\r\n");
      out.write("        <a href=\"javascript:void(0);\" class=\"link icon-only\"><i class=\"icon icon_emoji voice\"></i></a>\r\n");
      out.write("        <div class=\"voice_btn\">按住&nbsp;说话</div>\r\n");
      out.write("        <a href=\"javascript:void(0);\" class=\"link icon-only\"><i class=\"icon icon_emoji _emoji\"></i></a>\r\n");
      out.write("        <a href=\"javascript:void(0);\" class=\"link icon-only option\"><i class=\"icon icon_emoji more_option\"></i></a>\r\n");
      out.write("        <a href=\"javascript:void(0);\" class=\"link send-message\"><span class=\"mes_send\">发送</span></a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div> \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"emoji_list_container\">\r\n");
      out.write("          <!-- Slider -->\r\n");
      out.write("          <div class=\"swiper-container\" >\r\n");
      out.write("            <div class=\"swiper-wrapper emoji_list\">\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"option_list_container\">\r\n");
      out.write("          <div class=\"swiper-container\" >\r\n");
      out.write("            <div class=\"swiper-wrapper option_list\">\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>   \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/jsp/common/taglibs.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("contextPath");
    // /WEB-INF/jsp/common/taglibs.jsp(9,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/common/taglibs.jsp(9,0) '${pageContext.request.contextPath}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(null);
    // /WEB-INF/jsp/common/taglibs.jsp(10,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("webAppTitle");
    // /WEB-INF/jsp/common/taglibs.jsp(10,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/common/taglibs.jsp(10,0) '奥马导购移动端管理系统'",_el_expressionfactory.createValueExpression("奥马导购移动端管理系统",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }
}
